#:schema node_modules/wrangler/config-schema.json
name = "krishna-glass-redesign"
pages_build_output_dir = "." # Assumes static files are at root

[vars]
# You can define environment variables here
ENVIRONMENT = "production"

[[routes]]
pattern = "krishnaglass.explyra.me/*"
script = "index.html" # In case of worker mode, but for Pages this isn't strictly needed if using static mode

# Cloudflare Pages specific settings
[site]
bucket = "."

[dev]
port = 8788
local_protocol = "https"
